import sqlite3
db=sqlite3.connect('twitterDB.db')
db.execute("CREATE TABLE tweets (id INTEGER PRIMARY KEY, tweetID VARCHAR(30) NOT NULL, tweet BLOB NOT NULL, archiveID INTEGER NOT NULL, position INTEGER NOT NULL)")
db.execute("CREATE TABLE archives (id INTEGER PRIMARY KEY, name VARCHAR(30) NOT NULL, ownerID INTEGER NOT NULL)")
db.execute("INSERT INTO archives (id, name, ownerID) VALUES (?,?,?)", (1, 'Olivias Stuff', 1))
db.execute("INSERT INTO archives (id, name, ownerID) VALUES (?,?,?)", (2, 'Olivias Stuff V2', 1))
db.execute("INSERT INTO archives (id, name, ownerID) VALUES (?,?,?)", (3, 'Zaras Stuff', 2))
db.execute("INSERT INTO archives (id, name, ownerID) VALUES (?,?,?)", (4, 'Chelseas Stuff', 3))
db.execute("INSERT INTO archives (id, name, ownerID) VALUES (?,?,?)", (5, 'Jodies Stuff', 4))
db.execute("CREATE TABLE archiveUsers (archiveID INTEGER NOT NULL, sharedUserID INTEGER NOT NULL)")
db.execute("INSERT INTO archiveUsers (archiveID, sharedUserID) VALUES (?,?)", (1,2))
db.execute("INSERT INTO archiveUsers (archiveID, sharedUserID) VALUES (?,?)", (2,3))
db.execute("INSERT INTO archiveUsers (archiveID, sharedUserID) VALUES (?,?)", (3,1))
db.execute("INSERT INTO archiveUsers (archiveID, sharedUserID) VALUES (?,?)", (4,4))
db.execute("INSERT INTO archiveUsers (archiveID, sharedUserID) VALUES (?,?)", (5,3))
db.execute("CREATE TABLE users (id INTEGER PRIMARY KEY, name char(30) NOT NULL, password char(30) NOT NULL)")
db.execute("INSERT INTO users (name,password) VALUES ('Olivia','Password')")
db.execute("INSERT INTO users (name,password) VALUES ('Zara','Password2')")
db.execute("INSERT INTO users (name,password) VALUES ('Chelsea','Password3')")
db.execute("INSERT INTO users (name,password) VALUES ('Jodie','Password4')")
db.commit()